name Run_Gradio_App

on
  push
    branches
      - main
  pull_request
    branches
      - main

jobs
  run
    runs-on ubuntu-latest
    
    steps
    - name Checkout code
      uses actionscheckout@v2
      
    - name Set up Python
      uses actionssetup-python@v2
      with
        python-version '3.8'  # You can specify the version of Python you need
    
    - name Install dependencies
      run 
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies listed in requirements.txt
    
    - name Run Gradio app
      run 
        python app.py  # Change this to the Python file you want to run (e.g., 'app.py')
